name: 2024-09-12
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  ProgrammersDay:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v3
      # run – произвольная bash-команда
      - run: make install
      - name: check calender
        run: make say-hello
      - name: is256dayOfTheYear
        run: make lint
      - name: congratulate-my-dudes
        run: make lint
      - name: wish them comfortable CICD
        run: make lint
      - run: make test
      - name: wish them always passing tests
        run: make lint
